export * from './function/depthForEach'
export * from './function/breadthForEach'
export * from './function/graph'
export * from './function/find'
export * from './function/shuffle'
export * from './function/doubleForEach'
export * from './function/forEachRight'
export * from './function/multiFieldSearch'
export * from './function/arrEq'
export * from './function/arrToMap'
export * from './function/chunk'
export * from './function/arrToTree'
export * from './function/delArrItem'
export * from './function/random'
export * from './function/diffCount'
export * from './function/toCurrency'
export * from './function/toPercent'
export * from './function/randomStr'
export * from './function/getUrlParam'
export * from './function/prefixZero'
export * from './function/loadScript'
export * from './function/element'
export * from './function/addElement'
export * from './function/blocked'
export * from './function/mergeIntersect'
export * from './function/randomColor'
export * from './function/escapeHtml'
export * from './function/randomIp'
export * from './function/isOdd'
export * from './function/runTask'

import Animation from './function/animation'
import Deque from './function/deque'
import Queue from './function/queue'
import Stack from './function/stack'

import Scheduling from './function/scheduling'

export * from './function/type'
export * from './function/platform'

export { Deque, Queue, Stack, Scheduling, Animation }
